- name: create /opt/tools/installers
  become: yes
  file:
    path: /opt
    state: directory
    mode: '777'

# We will do this later
# - name: install GoLand
#   shell: |
#      cd /opt
#      wget https://download.jetbrains.com/go/goland-2020.1.3.tar.gz?_ga=2.22135611.1405077787.1593888509-1739388871.1593888509
#      tar -xvf goland*
#      rm -rf goland*
#   args:
#      creates: /opt/GoLand-2020.1.3


# - name: install go binary
#   shell: |
#      cd /opt
#      wget https://dl.google.com/go/go1.14.4.linux-amd64.tar.gz
#      tar -C /usr/local -xzf go*.tar.gz
#   args:
#      creates: /usr/local/go

# - name: symlink in go binary
#   become: yes
#   shell: |
#       if [ ! -e /usr/bin/go ] ; then ln -s /usr/local/go/bin/go /usr/bin/go; fi

- name: Add golang APT repository
  become: yes
  apt_repository:
    validate_certs: no
    repo: 'ppa:longsleep/golang-backports'
    state: present
    update_cache: yes


- name: install golang and bison
  become: yes
  apt:
    name: ['golang-go', 'bison']
    state: present
    update_cache: yes

- name: install gvm
  shell: |
     curl -s -S -L https://raw.githubusercontent.com/moovweb/gvm/master/binscripts/gvm-installer > /opt/tools/installers/gvminstall.sh
     bash /opt/tools/installers/gvminstall.sh
     . /home/dhinman/.gvm/scripts/gvm
  args:
     creates: /opt/tools/installers/gvminstall.sh
