---

- name: Install gpg
  become: yes
  apt:
    name: ['gpg']
    state: installed
    update_cache: yes

- name: Import key for repo
  become: yes
  shell: |
     wget -qO - https://www.mongodb.org/static/pgp/server-4.2.asc | apt-key add -

- name: Create sources.list.d
  become: yes
  shell: |
     echo "deb http://repo.mongodb.org/apt/debian stretch/mongodb-org/4.2 main" | tee /etc/apt/sources.list.d/mongodb-org-4.2.list

- name: Install mongodb-org
  become: yes
  apt:
    name: ['mongodb-org']
    state: installed
    update_cache: yes
# After this, can start mongo like this:
#   mkdir ~/data
#   mongod --dbpath ~/data
#
# To test: in a second window
#   mongo
#     db.mycol1.insert({a:1})
#     db.mycol1.find()
#     db.mycol1.drop()
#     exit

- name: Install MongoDB Compass
  become: yes
  apt:
    deb: https://downloads.mongodb.com/compass/mongodb-compass_1.20.4_amd64.deb
# After this, you can run mongodb-compass
