---

- name: Install snap
  become: yes
  apt:
    name: ['snap']
    state: installed
    update_cache: yes

- name: Install snap packages
  become: yes
  shell: |
    snap install core
    snap install core18
