- name: create /opt
  become: yes
  file:
    path: /opt
    state: directory
    mode: '777'

- name: install GoLand
  shell: |
     cd /opt
     wget https://download.jetbrains.com/go/goland-2020.1.3.tar.gz?_ga=2.22135611.1405077787.1593888509-1739388871.1593888509
     tar -xvf goland*
     rm -rf goland*
  args:
     creates: /opt/GoLand-2020.1.2


- name: install go binary
  shell: |
     cd /opt
     wget https://dl.google.com/go/go1.14.4.linux-amd64.tar.gz
     tar -C /usr/local -xzf go*.tar.gz
  args:
     creates: /usr/local/go

- name: install bison
  become: yes
  apt:
    name: ['bison']
    state: installed
    update_cache: yes

- name: install gvm
  shell: |
     curl -s -S -L https://raw.githubusercontent.com/moovweb/gvm/master/binscripts/gvm-installer > /opt/gvminstall.sh
     bash /opt/gvminstall.sh
     source /home/dhinman262/.gvm/scripts/gvm
  args:
     creates: /opt/gvminstall.sh
