- name: create /opt
  become: yes
  file:
    path: /opt
    state: directory
    mode: '777'

- name: install GoLand
  shell: |
     cd /opt
     wget https://download.jetbrains.com/go/goland-2020.1.2.tar.gz?_ga=2.32718714.593149619.1591228392-1555125490.1591228392
     tar -xvf goland*


- name: install go binary
  shell: |
     cd /opt
     wget https://dl.google.com/go/go1.14.4.linux-amd64.tar.gz
     tar -C /usr/local -xzf go*.tar.gz
