- name: create /opt/tools/installers
  become: yes
  file:
    path: /opt/tools/installers
    state: directory
    mode: '777'

- name: detect if nvm installed
  stat:
    path: /home/dhinman/.nvm
  register: nvm_dir
  ignore_errors: yes

- name: fetch nvm
  shell: curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/v0.39.1/install.sh > /opt/tools/installers/nvminstall.sh
  when: nvm_dir.stat.exists == False

- name: install nvm
  become: yes
  shell: /bin/bash /opt/tools/installers/nvminstall.sh
  when: nvm_dir.stat.exists == False

# This was the old way; the new way first adds a repo to the system
# - name: install nodejs
#   shell: source {{ ansible_env.HOME }}/.nvm/nvm.sh && nvm install --lts=boron
#   when: nvm_dir.stat.exists == False
#   args:
#     executable: /bin/bash

- name: Install nodejs
  become: yes
  apt:
    name: ['yarn']
    state: installed
    update_cache: yes
  
- name: Get Yarn apt key
  become: yes
  apt_key:
    url: https://dl.yarnpkg.com/debian/pubkey.gpg
    state: present

- name: Add Yarn repo
  become: yes
  apt_repository:
    repo: deb https://dl.yarnpkg.com/debian/ stable main
    state: present

- name: Install Yarn
  become: yes
  apt:
    name: ['yarn']
    state: installed
    update_cache: yes
  