- name: Install common pre-requisites using apt
  become: yes
  apt:
    name: ['curl', 'git', 'default-jdk', 'build-essential']
    state: present
    update_cache: yes

- name: Install missing apps using apt
  become: yes
  apt:
    name: ['emacs', 'lsof', 'gimp', 'gimp-plugin-registry', 'python-pip', 'nemo', 'jq']
    state: present
    update_cache: yes

- name: Install the basic apps from the list
  become: yes
  apt:
    name: ['audacity', 'brasero', 'filezilla', 'gparted', 'gscan2pdf', 'inkscape', 'vlc', 'wine', 'winetricks', 'wireshark']
    state: present
    update_cache: yes
    
- name: prepare eula 
  debconf:
    name: virtualbox-ext-pack
    question: virtualbox-ext-pack/license
    value: true
    
- name: Install the next wave
  become: yes
  apt:
    name: ['handbrake', 'virtualbox', 'virtualbox-dkms', 'virtualbox-guest-additions-iso', 'virtualbox-ext-pack']
    state: present
    update_cache: yes

