- name: Install common pre-requisites using apt
  become: yes
  apt:
    name: ['curl', 'git', 'default-jdk', 'build-essential']
    state: present
    update_cache: yes

- name: Install missing apps using apt
  become: yes
  apt:
    name: ['emacs', 'lsof', 'gimp', 'gimp-plugin-registry', 'python-pip', 'nemo', 'jq', 'git-delta']
    state: present
    update_cache: yes

- name: Install the basic apps from the list
  become: yes
  apt:
    name: ['audacity', 'brasero', 'filezilla', 'gparted', 'gscan2pdf', 'inkscape', 'vlc', 'wine', 'winetricks', 'wireshark']
    state: present
    update_cache: yes
    
- name: prepare eula 
  debconf:
    name: virtualbox-ext-pack
    question: virtualbox-ext-pack/license
    vtype: boolean
    value: true
    
- name: Install the next wave
  become: yes
  apt:
    name: ['handbrake', 'virtualbox', 'virtualbox-dkms', 'virtualbox-guest-additions-iso', 'virtualbox-ext-pack']
    state: present
    update_cache: yes

- name: Install Chrome from the package directly
  apt:
    deb: https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb

- name: Install gnome-keyring
  become: yes
  apt:
    name: ['gnome-keyring']
    state: present
    update_cache: yes

- name: Install Visual Studio Code from a deb
  apt:
    deb: https://code.visualstudio.com/sha/download?build=stable&os=linux-deb-x64

- name: Install veracrypt from a deb
  apt:
    deb: https://launchpad.net/veracrypt/trunk/1.25.9/+download/veracrypt-1.25.9-Debian-11-amd64.deb
    

- name: Install wave 3
  become: yes
  apt:
    name: ['calibre', 'calibre-bin', 'devede', 'htop', 'meld', 'openshot', 'openshot-doc', 'seahorse'. 'gpg', 'gpg-agent', 'simplescreenrecorder']
    state: present
    update_cache: yes

