---

- name: create /opt
  become: yes
  file:
    path: /opt
    state: directory
    mode: '777'

- name: Download libreoffice
  get_url:
    url: https://download.documentfoundation.org/libreoffice/stable/7.0.2/deb/x86_64/LibreOffice_7.0.2_Linux_x86-64_deb.tar.gz
    dest: /opt/LibreOffice_7.0.2_Linux_x86-64_deb.tar.gz

- name: Unarchive libreoffice
  unarchive:
    src: /opt/LibreOffice_7.0.2_Linux_x86-64_deb.tar.gz
    dest: /opt

- name: Install libreoffice
  become: yes
  shell: |
     cd /opt/LibreOffice_7.0.2.2_Linux_x86-64_deb/DEBS
     sudo dpkg -i *.deb

- name: Install libreoffice icons
  become: yes
  apt:
    name: ['libreoffice-gnome']
    state: installed
    update_cache: yes

- name: Install filezilla
  become: yes
  apt:
    name: ['filezilla']
    state: installed
    update_cache: yes
